### ISSUE TITLE
ERROR  Failed to compile with 9 errors  

### ISSUE THREAD

**Issue by smuki** [vincentzyc/form-design-next#1]
ERROR  Failed to compile with 9 errors                                                                                                                                                        8:29:43 AM

These relative modules were not found:

* ./Agreement in ./src/assets/js/widget/index.js
* ./Assist in ./src/assets/js/widget/index.js
* ./Button in ./src/assets/js/widget/index.js
* ./Form in ./src/assets/js/widget/index.js
* ./Marquee in ./src/assets/js/widget/index.js
* ./Sms in ./src/assets/js/widget/index.js
* ./Video in ./src/assets/js/widget/index.js
* ./Wechat in ./src/assets/js/widget/index.js
* ./labeltext in ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/@vue/cli-service/node_modules/vue-loader-v16/dist??ref--0-1!./src/components/PageConfig/WidgetConfig/StyleConfig/style.vue?vue&type=script&lang=ts

**Comment by vincentzyc** [comment]
文件名大小写问题，已修复
